on:
  push:
    tags: ["v*"]

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: Get version from tag
      run: echo "VERSION=${GITHUB_REF_NAME/#v}" | tee $GITHUB_ENV

    - name: Set release title
      run: echo "TITLE=unpoka-${VERSION}" | tee $GITHUB_ENV

    - name: Publish all targets
      uses: ./.github/actions/publish-all
      with:
        title: ${{ env.TITLE }}
