on:
  push:
    tags: ['v*']

defaults:
  run:
    shell: bash

jobs:
  publish:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Get tag version
      run: echo "VERSION=${GITHUB_REF_NAME/#v}" | tee $GITHUB_ENV
    
    - name: Set release title
      run: echo "TITLE=unpoka ${VERSION}" | tee $GITHUB_ENV
    
    - name: Publish
      run: dotnet publish unpoka -o "publish/${TITLE}" -p:PublishSingleFile=true --no-self-contained
    
    - name: Copy dist files
      run: cp -r dist/* "publish/${TITLE}"
    
    - name: Upload artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ env.TITLE }}
        path: publish
